### ISSUE TITLE
[Bug] TemporalClient timing out 

### ISSUE THREAD

**Issue by AdnanSoftic** [temporalio/sdk-dotnet#158]
### What are you really trying to do?

We have a .NET 7 Web API that registers a TemporalClient like:

```
builder.Services.AddTemporalClient(options =>
    {
        options.TargetHost = builder.Configuration.GetValue<string>("Temporal:Host");
        options.Namespace = builder.Configuration.GetValue<string>("Temporal:Namespace") ?? "default";
    
        var privateKey = builder.Configuration.GetValue<string>("Temporal:PrivateKey");
        var publicCertificate = builder.Configuration.GetValue<string>("Temporal:PublicCertificate");

        if (!string.IsNullOrEmpty(privateKey) && !string.IsNullOrEmpty(publicCertificate))
        {
            options.Tls = new TlsOptions
            {
                ClientCert = Encoding.UTF8.GetBytes(publicCertificate.Replace("******", "\n")),
                ClientPrivateKey = Encoding.UTF8.GetBytes(privateKey.Replace("******", "\n"))
            };
        }
    });
```

### Describe the bug

In our TST environment we are connecting to a Temporal Cloud service and things are working as expected for for a certain period. After a day or two We have noticed that Temporal client loses connection with temporal Cloud and is unable to start any new Workflow(s). The result is a following exception:

```
2023-11-17T12:38:53.347909835Z [12:38:53 ERR] An unhandled exception has occurred while executing the request.
2023-11-17T12:38:53.347943176Z Temporalio.Exceptions.RpcException: Timeout expired
2023-11-17T12:38:53.347949201Z    at Temporalio.Bridge.Client.CallAsync[T](RpcService service, String rpc, IMessage req, MessageParser`1 resp, Boolean retry, IEnumerable`1 metadata, Nullable`1 timeout, Nullable`1 cancellationToken)
2023-11-17T12:38:53.347953385Z    at Temporalio.Client.TemporalConnection.InvokeRpcAsync[T](RpcService service, String rpc, IMessage req, MessageParser`1 resp, RpcOptions options)
2023-11-17T12:38:53.347957739Z    at Temporalio.Client.WorkflowService.StartWorkflowExecutionAsync(StartWorkflowExecutionRequest req, RpcOptions options)
2023-11-17T12:38:53.347962584Z    at Temporalio.Client.TemporalClient.Impl.StartWorkflowInternalAsync[TWorkflow,TResult](StartWorkflowInput input)
2023-11-17T12:38:53.347966881Z    at Temporalio.Client.TemporalClient.Impl.StartWorkflowAsync[TWorkflow,TResult](StartWorkflowInput input)
2023-11-17T12:38:53.347971070Z    at Temporalio.Client.TemporalClient.StartWorkflowAsync[TWorkflow,TResult](Expression`1 workflowRunCall, WorkflowOptions options)
2023-11-17T12:38:53.347975844Z    at ******************.Facade.Controllers.B2BPersonsController.OnboardB2BPerson(B2BPersonOnboardingRequest b2BPersonOnboardingRequest) in /src/WebApi/Controllers/B2BPersonsController.cs:line 111
```

### Minimal Reproduction

Unable to reproduce since the issue is occurring sporadically.
 
### Environment/Versions

- OS and processor: Linux
- Temporal Version: .NET SDK version: 0.1.0-beta1
- Are you using Docker or Kubernetes or building Temporal from source? - No. We are using Temporal Cloud.

### Additional context

Our Client application is running in Azure Container environment.

**Comment by cretz** [comment]
We have seen other situations of this and have turned on client keep alive by default in beta 2 (#138). It is possible that Azure is closing idle outbound connections. Can you upgrade to beta 2 and confirm this issue no longer occurs?

**Comment by AdnanSoftic** [comment]
@cretz I will update to beta2 and monitor throughout the next week.
Regarding Azure closing outbound connections, I am really not sure how that works. From our side we configure number of instances of an image running in the Container environment, where we always have at least one instance running.

Thank you for your feedback.

**Comment by cretz** [comment]
:+1: No prob. We have seen other issues with users there hitting these idle timeouts and this client keep alive did seem to resolve it. I will close the issue now, but feel free to reopen if it persists (or come join us on `#dotnet-sdk` on Slack at https://t.mp/slack or our forums at https://community.temporal.io).

**Comment by geoffreytran** [comment]
Also running into this issue with the 1.0 sdk. Is there a way to check if the connection is disconnected and reconnect?

**Comment by cretz** [comment]
No, the connection is supposed to automatically reconnect internally, and keep alive is enabled by default which should reconnect when it is seen as down.

**Comment by geoffreytran** [comment]
That's good to know! Odd thing is, when this exception occurs, with the default keep alive settings, it doesn't seem to recover. We have an exponential retry configured to retry the start workflow call, but it keeps getting the timeout expired exception until the app is restarted.

It's been elusive to reproduce as it seems to happen sporadically, so I haven't been able to debug deeper yet, but just wanted to leave a comment in case anyone else is running into the same issue.
